---
title: "Part_1"
author: "Gael Mariani"
date: "`r Sys.Date()`"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::load_all()
```

## Install missing packages from GitHub

```{r}
# First run the following command to install packages from CRAN
devtools::install_deps()

# For problematic packages, install from Github
devtools::install_github("ggobi/ggally")

```


## 1. Relationships between NCS implementation and SDG achievement

```{r message = FALSE}
raw_dat <- NCSSDGproj::read_matrix()

pathSDG <- NCSSDGproj::load_SDG_icon()
pathNCS <- NCSSDGproj::load_NCS_icon()

icon_SDG <- NCSSDGproj::format_icons(pathSDG, icon_SDG = TRUE)
icon_NCS <- NCSSDGproj::format_icons(pathNCS, icon_SDG = FALSE)

data_long <- NCSSDGproj::matrix_to_longDF(matrix01 = raw_dat)
SDG_matrix <- NCSSDGproj::matrix_SDG(data_long = data_long)
SDG_net <- NCSSDGproj::matrix_to_network(matrix = SDG_matrix, mode1 = "P" , mode2 = "A")

NCSSDGproj::plot_network(SDG_net, SDG_matrix,
                         icon_SDG = icon_SDG,icon_NCS = icon_NCS,
                         nodes_col = c(rep("#228B22", 4), rep("#5EA9A2", 4), rep("#1134A6", 3)),
                         save = TRUE)

data_pour <- NCSSDGproj::perc_SDG(data_long = data_long)

NCSSDGproj::barplot_percSDG(data_plot = data_pour, 
                            color = c("#1134A6", "#5EA9A2", "#228B22"), #mar, coast, terr
                            save = TRUE, 
                            legend = TRUE)

Fig2 <- NCSSDGproj::Figure2(save = TRUE)

```


## 2. Complementarity of NCS in target's achievement

```{r}
matrix01 <- NCSSDGproj::contingency_mat_targets(raw_dat)

info_NCS <- NCSSDGproj::NCS_info(matrix01)

# ca <- NCSSDGproj::Correspondance_Analysis(matrix01 = matrix01)



axis2_targ <- NCSSDGproj::SDG_contrib_tbl() 

contri_CA <- NCSSDGproj::CA_contri_vars(matrix01 = matrix01, 
                                        axis2_targ = axis2_targ,
                                        colNCS_ter = "#228B22", 
                                        colNCS_coast = "#5EA9A2",
                                        colNCS_mar = "#1134A6")

NCSSDGproj::Figure3(data = contri_CA[["CorresAna"]],
                    targ_contrib12 = contri_CA[["col_contrib"]][["axe12"]],
                    data_arrow = contri_CA[["data_arrow"]],
                    colNCS_ter = "#228B22", 
                    colNCS_coast = "#5EA9A2",
                    colNCS_mar = "#1134A6",
                    save = TRUE)

################################# PAS LA PEINE DE FAIRE TOURNER
#################################

#NCSSDGproj::plot_CorresAna(ca = ca[["Correspondance Analysis"]],
#                           ca_subset = ca[["CA_subset"]],
#                           NCS_info = info_NCS,
#                           colors = c("#66c2a5", "#e5c494", "#8da0cb"),
#                           ellipse = TRUE,
#                           hull = FALSE, 
#                           save = TRUE)

test <- NCSSDGproj::circular_data_Insurance()


data = contri_CA[["CorresAna"]]
contri_CA[["col_contrib"]][["axe12"]]$targ_contrib12 
data_arrow = contri_CA[["data_arrow"]]
TOP20_1 = contri_CA[["TOP20_axis1_targ"]]
TOP20_2 = contri_CA[["TOP20_axis2_targ"]]
colNCS_ter = "#228B22"
colNCS_coast = "#5EA9A2"
colNCS_mar = "#1134A6"

ymin <- -5
ymax <- 6.5
ytitle <- -5


data_contrib <- contri_CA[["CorresAna"]]
targ_contrib12 <- contri_CA[["col_contrib"]][["axe12"]]
NCS_contrib12 <- contri_CA[["row_contrib"]][["axe12"]]
data_arrow <- contri_CA[["data_arrow"]]
TOP20_axis1 <- contri_CA[["TOP20_axis1_targ"]]
TOP20_axis2 <- contri_CA[["TOP20_axis2_targ"]]
TOP20 <- contri_CA[["TOP20_axis2_targ"]]


col_sust <- "#FACA0F"
col_unsust <- "#762a83"
col_oth <- "#e0e0e0" 
################################# 

```


## 3. Target Insurance and null models

```{r message=FALSE, warning=FALSE}
mod_nest_res <- NCSSDGproj::NullModels(matrix01 = matrix01, rawdata = raw_dat, NMalgo = "quasiswap", NESTmethod ="NODF",
                                       Nrun = 5, Nsim = 5, TargetInsurance = FALSE)

TUI_TOI_res <- NCSSDGproj::NullModels(matrix01 = matrix01, rawdata = raw_dat, NMalgo = "r00", NESTmethod = "NODF",
                                      Nrun = 100, Nsim = 100, TargetInsurance = TRUE)


null_data <- NCSSDGproj::null_data_CircPlot(matrix01 = matrix01, nsim = 10)

data_Insurance <- NCSSDGproj::Insurance_data2plot(matrix01 = matrix01, Ntarget = ncol(matrix01)) 
SDG_info <- NCSSDGproj::SDG_infos(matrix01 = matrix01)
NCS_info <- NCSSDGproj::NCS_info(matrix01 = matrix01)



data_circu <- NCSSDGproj::circular_data_Insurance(data_Insurance = data_Insurance, 
                                                  data_long = data_long, 
                                                  SDG_info = SDG_info, 
                                                  NCS_info = NCS_info)

NCSSDGproj::legend_verti(data_plot = data_pour, color = c("#1134A6", "#5EA9A2", "#228B22"))

NCSSDGproj::circular_plot_Insurance(data = data_circu[[1]], 
                                    label_data = data_circu[[2]],
                                    base_data = data_circu[[3]],
                                    grid_data = data_circu[[4]],
                                    SDG_info = SDG_info,
                                    colNCS_ter = "#228B22", 
                                    colNCS_coast = "#5EA9A2",
                                    colNCS_mar = "#1134A6",
                                    iconSDG = icon_SDG,
                                    save = TRUE)

################################# PAS LA PEINE DE FAIRE TOURNER
################################
NCSSDGproj::Insurance_plot(data = data_Insurance, 
                           TI = 5.20, 
                           TUI_obs = round(TUI_TOI_res$Val_Obs[1], 3) * 100, 
                           TUI_null = round(TUI_TOI_res$Val_nulls[1], 4) * 100,
                           obs_col = "#0000EB", 
                           null_col = "#E60000", 
                           save = TRUE) 

################################
```




## Unipartite network

```{r message = FALSE, warning = FALSE}
 
conting_mat <- NCSSDGproj::contingency_mat_targets(raw_dat = raw_dat)

netw_Unip <- NCSSDGproj::network_uniP(contin_mat_target = conting_mat, 
                                      method = "fruchtermanreingold", 
                                      colNCS_ter = "#66c2a5", 
                                      colNCS_coast = "#e5c494",
                                      colNCS_mar = "#8da0cb", 
                                      colTARG = "grey70")

NCSSDGproj::unipart_plot(netw = netw_Unip, 
                         colNCS_ter = "#66c2a5", 
                         colNCS_coast = "#e5c494", 
                         colNCS_mar = "#8da0cb", 
                         save = TRUE)


```


